// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const {themes} = require('prism-react-renderer');
const lightTheme = themes.github;
const darkTheme = themes.dracula;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'SDevelopement Wiki',
  tagline: 'Complete documentation for SPlugins : ExecutableItems, ExecutableBlocks, ExecutableEvents, and more',
  favicon: 'img/ssomarlogo2.png',

  // Set the production url of your site here
  url: 'https://ssomar-developement.github.io',
  // Set the /<baseUrl>/ pathname under which your site is served
  baseUrl: '/',

  // GitHub pages deployment config.
  organizationName: 'Ssomar-Developement', // Usually your GitHub org/user name.
  projectName: 'Wiki', // Usually your repo name.

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  markdown: {
    hooks: {
      onBrokenMarkdownImages: 'warn',
    },
  },

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  clientModules: [
    require.resolve('./src/components/ResizableSidebar.js'),
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl: 'https://github.com/Ssomar-Developement/Wiki/edit/main/',
          // Show last update time and author
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          // Filter out unlisted pages and partials from autogenerated sidebars
          async sidebarItemsGenerator({defaultSidebarItemsGenerator, ...args}) {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            // Filter out items marked as unlisted: true and _partials folder
            return sidebarItems.filter((item) => {
              // Filter out _partials folder
              if (item.type === 'category' && item.label === '_partials') {
                return false;
              }
              // Keep category items, only filter doc items
              if (item.type === 'category') {
                // Recursively filter items in categories
                if (item.items) {
                  item.items = item.items.filter((subItem) => !subItem.unlisted);
                }
                return true;
              }
              // Filter out unlisted doc items
              return !item.unlisted;
            });
          },
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: 'img/docusaurus-social-card.jpg',
      announcementBar: {
        id: 'welcome_announcement',
        content: '🎉 <strong>Welcome to our new Wiki!</strong> 🚀 Explore our completely redesigned documentation with improved search, better navigation, and enhanced readability.',
        backgroundColor: '#5b5ee6',
        textColor: '#ffffff',
        isCloseable: true,
      },
      colorMode: {
        defaultMode: 'dark',
        disableSwitch: false,
        respectPrefersColorScheme: false,
      },
      docs: {
        sidebar: {
          autoCollapseCategories: true,
          hideable: true,
        },
      },
      navbar: {
        title: 'SDevelopement Wiki',
        logo: {
          alt: 'SPlugins Logo',
          src: 'img/ssomarlogo2.png',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'mainSidebar',
            position: 'left',
            label: 'Plugins Wiki',
          },
          {
            to: '/purchase',
            position: 'left',
            label: 'Purchase',
          },
          {
            to: '/discord',
            position: 'left',
            label: 'Discord',
          },
          {
            to: '/ssomar-services',
            position: 'left',
            label: 'Products for developers',
          },
          {
            type: 'search',
            position: 'right',
          },
          {
            href: 'https://github.com/Ssomar-Developement',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {
                label: 'Getting Started',
                to: '/docs/intro',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'Discord',
                href: 'https://discord.com/invite/TRmSwJaYNv',
              },
            ],
          },
          {
            title: 'More',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/Ssomar-Developement',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Score Plugins. Built with Docusaurus.`,
      },
      prism: {
        theme: lightTheme,
        darkTheme: darkTheme,
        additionalLanguages: ['java', 'yaml'],
      },
    }),
};

module.exports = config;
