/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Fully autogenerated sidebar based on the docs folder structure
  // Controlled by _category_.json files in each folder
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from the entire docs folder
    },
  ],
};

module.exports = sidebars;
