/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Tools for all Plugins [Score]',
      items: [
        {
          type: 'category',
          label: 'Custom Commands',
          items: [
            'tools-for-all-plugins-score/custom-commands/player-and-target-commands',
            'tools-for-all-plugins-score/custom-commands/mixed-commands-player-and-entity',
            'tools-for-all-plugins-score/custom-commands/entity-commands',
            'tools-for-all-plugins-score/custom-commands/block-commands',
            'tools-for-all-plugins-score/custom-commands/item-commands',
            'tools-for-all-plugins-score/custom-commands/utility-commands',
          ],
        },
        {
          type: 'category',
          label: 'Custom Conditions',
          items: [
            'tools-for-all-plugins-score/custom-conditions/README',
            'tools-for-all-plugins-score/custom-conditions/player-and-target-conditions',
            'tools-for-all-plugins-score/custom-conditions/entity-conditions',
            'tools-for-all-plugins-score/custom-conditions/block-conditions',
            'tools-for-all-plugins-score/custom-conditions/world-conditions',
            'tools-for-all-plugins-score/custom-conditions/item-conditions',
            'tools-for-all-plugins-score/custom-conditions/placeholder-conditions',
            'tools-for-all-plugins-score/custom-conditions/custom-ei-conditions',
          ],
        },
        'tools-for-all-plugins-score/custom-projectiles',
        'tools-for-all-plugins-score/placeholders',
        'tools-for-all-plugins-score/score-particles',
        'tools-for-all-plugins-score/score-variables',
        'tools-for-all-plugins-score/blocks-hardnesses',
        'tools-for-all-plugins-score/compatible-plugins',
        {
          type: 'category',
          label: 'General Questions | Guides',
          items: [
            'tools-for-all-plugins-score/general-questions-or-guides/README',
            'tools-for-all-plugins-score/general-questions-or-guides/technical-level-info',
            'tools-for-all-plugins-score/general-questions-or-guides/score',
            'tools-for-all-plugins-score/general-questions-or-guides/math-formulas',
          ],
        },
        'tools-for-all-plugins-score/custom-triggers',
      ],
    },
    {
      type: 'category',
      label: 'ExecutableItems',
      link: {
        type: 'doc',
        id: 'executableitems/information-ei',
      },
      items: [
        'executableitems/information-ei',
        'executableitems/commands-and-permissions',
        'executableitems/mc-versions-compatibility',
        'executableitems/special-behaviors',
        { type: 'autogenerated', dirName: 'executableitems/configurations' },
        { type: 'autogenerated', dirName: 'executableitems/questions-or-guides' },
        'executableitems/developer-api',
      ],
    },
    {
      type: 'category',
      label: 'ExecutableBlocks',
      link: {
        type: 'doc',
        id: 'executableblocks/information-eb',
      },
      items: [
        'executableblocks/information-eb',
        'executableblocks/commands-and-permissions',
        'executableblocks/developer-api',
      ],
    },
    {
      type: 'category',
      label: 'ExecutableEvents',
      link: {
        type: 'doc',
        id: 'executableevents/information-ee',
      },
      items: [
        'executableevents/information-ee',
        'executableevents/commands-and-permissions',
      ],
    },
    {
      type: 'category',
      label: 'MyFurniture',
      link: {
        type: 'doc',
        id: 'myfurniture/information-mf',
      },
      items: [
        'myfurniture/information-mf',
        'myfurniture/commands-and-permissions',
      ],
    },
    {
      type: 'category',
      label: 'ExecutableCrafting',
      link: {
        type: 'doc',
        id: 'executablecrafting/information-ec',
      },
      items: [
        'executablecrafting/information-ec',
        'executablecrafting/commands-and-permissions',
      ],
    },
    {
      type: 'category',
      label: 'AI Chat Moderation',
      items: [
        'ai-chat-moderation/information-acm',
        'ai-chat-moderation/configurations',
        'ai-chat-moderation/commands-and-permissions',
      ],
    },
    {
      type: 'category',
      label: 'CustomPiglinsTrades',
      items: [
        'custompiglinstrades/information-cpt',
        'custompiglinstrades/commands-and-permissions',
        'custompiglinstrades/compatible-plugins',
      ],
    },
    {
      type: 'category',
      label: 'ScreenShop',
      items: [
        'screenshop/information-screenshop',
      ],
    },
    {
      type: 'category',
      label: 'Team & Donations',
      items: [
        'team-and-donations/contact-support-us',
      ],
    },
  ],
};

module.exports = sidebars;
